platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/PluginsBuilderCocoaPods.git'
source 'git@github.com:CocoaPods/Specs.git'


target 'ZappPushPluginFirebase-iOS_Example' do
  pod 'ZappPushPluginFirebase', :path => '../ZappPushPluginFirebase.podspec'
end
